<a href="https://colab.research.google.com/github/sugban/REDI-Data-Analytics-/blob/main/exercises_lesson03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### Import pandas library using alias pd.

In [ ]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df. Use the first column as index.

In [ ]:
df = pd.read_csv('data/Recipes.csv', index_col=0)
df

vegetarian  glutenFree  ...  CaffeineAmount  CaffeinepercentOfDailyNeed
0          True        True  ...             NaN                         NaN
1          True        True  ...             NaN                         NaN
2         False       False  ...            9.89                        3.30
3          True       False  ...             NaN                         NaN
4         False        True  ...             NaN                         NaN
..          ...         ...  ...             ...                         ...
145       False        True  ...             NaN                         NaN
146        True       False  ...           10.69                        3.56
147        True        True  ...             NaN                         NaN
148        True        True  ...             NaN                         NaN
149        True        True  ...             NaN                         NaN

[150 rows x 78 columns]

#### Print the type of variable df.

In [ ]:
type(df)

pandas.core.frame.DataFrame

#### Print the number of columns and number of rows of the df DataFrame.

In [ ]:
df.shape

(150, 78)

#### What are the names of the columns in df?

In [ ]:
df.columns

Index(['vegetarian', 'glutenFree', 'dairyFree', 'veryHealthy', 'healthScore',
       'aggregateLikes', 'id', 'title', 'pricePerServing', 'readyInMinutes',
       'servings', 'sourceUrl', 'CaloriesAmount', 'CaloriespercentOfDailyNeed',
       'FatAmount', 'FatpercentOfDailyNeed', 'SaturatedFatAmount',
       'SaturatedFatpercentOfDailyNeed', 'CarbohydratesAmount',
       'CarbohydratespercentOfDailyNeed', 'NetCarbohydratesAmount',
       'NetCarbohydratespercentOfDailyNeed', 'SugarAmount',
       'SugarpercentOfDailyNeed', 'CholesterolAmount',
       'CholesterolpercentOfDailyNeed', 'SodiumAmount',
       'SodiumpercentOfDailyNeed', 'ProteinAmount',
       'ProteinpercentOfDailyNeed', 'FiberAmount', 'FiberpercentOfDailyNeed',
       'VitaminB6Amount', 'VitaminB6percentOfDailyNeed', 'ManganeseAmount',
       'ManganesepercentOfDailyNeed', 'SeleniumAmount',
       'SeleniumpercentOfDailyNeed', 'PotassiumAmount',
       'PotassiumpercentOfDailyNeed', 'VitaminB2Amount',
       'VitaminB2per

#### Rename column id to RecipeId. Drop column "veryHealthy".

In [ ]:
NewNames={'id':'RecipeId'}
df_alternative = df.rename(mapper=NewNames, axis=1)
df_alternative[:3]

vegetarian  glutenFree  ...  CaffeineAmount  CaffeinepercentOfDailyNeed
0        True        True  ...             NaN                         NaN
1        True        True  ...             NaN                         NaN
2       False       False  ...            9.89                         3.3

[3 rows x 78 columns]

In [ ]:
df_alternative = df_alternative.drop(labels='veryHealthy', axis=1)
df_alternative[:3]

vegetarian  glutenFree  ...  CaffeineAmount  CaffeinepercentOfDailyNeed
0        True        True  ...             NaN                         NaN
1        True        True  ...             NaN                         NaN
2       False       False  ...            9.89                         3.3

[3 rows x 77 columns]

#### Some questions to think of for yourself. Feel free to ask us if you are in doubt, we are open for a discussion! :)

1. Are there any other columns in this dataset that you would consider a candidate for the index column? Why isn't is always a good idea to use a string as index?
2. Take a closer look at arguments "axis" and "inplace" in functions drop(...) and rename(...). Maybe google for documentation if you are not sure what they mean.
        What happens if you wanted to rename a column that is not there?
        What happens if you set the argument inplace=True? 

In [ ]:
df_alternative.set_index('title',inplace=True)

In [ ]:
df_alternative

vegetarian  ...  CaffeinepercentOfDailyNeed
title                                                          ...                            
Banana Blueberry Pancakes                                True  ...                         NaN
Basil and Orange Confit Compound Butter                  True  ...                         NaN
Black Bottom Banana Bars                                False  ...                        3.30
The Best Raw Chocolate Chip Cookies                      True  ...                         NaN
Mediterranean Spinach Artichoke Dip                     False  ...                         NaN
...                                                       ...  ...                         ...
Chicken Sausage, White Bean and Cabbage Soup            False  ...                         NaN
Pinot Noir Brownies                                      True  ...                        3.56
Cauliflower Chickpea Stew                                True  ...                         NaN
Sautéed Balsamic Green Beans With Cherry Tomatoes        True  ...                         NaN
Indian-Style Dill and Turmeric Potato Salad              True  ...                         NaN

[150 rows x 76 columns]

#### Import pandas library using alias pd.

In [ ]:
import pandas as pd

#### Load file recipes.csv from the data subfolder and store it in a variable df_ex1. Use the first column as index.

In [ ]:
df_ex1=pd.read_csv('Recipes.csv',index_col=0)
df_ex1.head(5)

vegetarian  glutenFree  ...  CaffeineAmount  CaffeinepercentOfDailyNeed
0        True        True  ...             NaN                         NaN
1        True        True  ...             NaN                         NaN
2       False       False  ...            9.89                         3.3
3        True       False  ...             NaN                         NaN
4       False        True  ...             NaN                         NaN

[5 rows x 78 columns]

#### See if the 34th recipe on the list is vegetarian (remember the 0-based indexing!). Please do this in 4 different ways. Be careful with how .iloc and .loc handle things.

In [ ]:
df_ex1['vegetarian'][35]

False

In [ ]:
df_ex1.vegetarian[35]

False

In [ ]:
df_ex1.iloc[35,0]

False

In [ ]:
df_ex1.loc[35,'vegetarian']

False

#### Choose columns with the following info and in the following order: title, price and if it is vegetarian

In [ ]:
df1=df_ex1[['title','pricePerServing','vegetarian']]
df1

title  ...  vegetarian
0                            Banana Blueberry Pancakes  ...        True
1              Basil and Orange Confit Compound Butter  ...        True
2                             Black Bottom Banana Bars  ...       False
3                  The Best Raw Chocolate Chip Cookies  ...        True
4                  Mediterranean Spinach Artichoke Dip  ...       False
..                                                 ...  ...         ...
145       Chicken Sausage, White Bean and Cabbage Soup  ...       False
146                                Pinot Noir Brownies  ...        True
147                          Cauliflower Chickpea Stew  ...        True
148  Sautéed Balsamic Green Beans With Cherry Tomatoes  ...        True
149        Indian-Style Dill and Turmeric Potato Salad  ...        True

[150 rows x 3 columns]

#### And now the same for recipes number from 24 to 29

In [ ]:
df1.iloc[24:29]

title  pricePerServing  vegetarian
24  Green Beans with Garlic Chips            83.90        True
25     Pandan Thumbprint Biscuits            54.26       False
26                  Lamb Moussaka           528.50       False
27         Easy Eggplant Parmesan           195.51        True
28                      Peach Pie           173.52        True

#### Play with some slicing and accesing. Do you understand the result that you obtain from different trials? Please feel free to ask us about what you see! :)

#### Notice which slicing methods are inclusive and which of them are exclusive. Try to figure your favourite way of accesing / slicing and remember that sometimes some of them make more sense than the others. 

### Class-exercise 2

In [1]:
import numpy as np

1. Create a 2-d and 3-d numpy integer array 

In [2]:
arr_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [3]:
arr_3D = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
arr_3D

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

2. Create a 2X2 integer array and show it's dimensions

In [10]:
arr=np.array([[1,2],[3,4]])
arr.ndim

2

In [11]:
arr.shape

(2, 2)

3. Create a numpy array and  print the sum of third and fourth elements from the array 

In [13]:
numarr= np.array([4,6,8,1,3,7,9])
sumarr=numarr[2]+numarr[3] # sum of third and forth element
sumarr

9

4. Slice the below array to get the the second item to the excluding fifth item

arr = np.array([10, 15, 20, 25, 30, 35, 40])

In [24]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[0:4]

array([10, 15, 20, 25])

5. Try example 4. using STEP method

In [25]:
arr[0:4:2]

array([10, 20])

6. Create a integer array and change data type from integer to boolean



In [ ]:
np.array([0,1,0,1,2,3],dtype=bool)

array([False,  True, False,  True,  True,  True])

7. Use NumPy syntax to check the shape of an array.

arr = np.array([1, 2, 3, 4, 5])

In [16]:
arr = np.array([1, 2, 3, 4, 5])
arr.shape

(5,)

8. Find the indexes where the values are even:

arr = [16, 8, 3, 7, 15, 24]

In [17]:
arr = [16, 8, 3, 7, 15, 24]

indexes=[i for i in range(len(arr)) if arr[i] % 2 == 0]
indexes

[0, 1, 5]

9. Create a numpy array of 5 person names and sort the values alpbabetically

In [18]:
arr = np.array(['Sugandh', 'Preeti', 'Bhagwati','Aniza','Madiha','Jyoti'])

np.sort(arr)

array(['Aniza', 'Bhagwati', 'Jyoti', 'Madiha', 'Preeti', 'Sugandh'],
      dtype='<U8')

10. Use the correct NumPy method to return a sorted array.

  arr = np.array([3, 2, 0, 1])

In [19]:
arr = np.array([3, 2, 0, 1])
np.sort(arr)

array([0, 1, 2, 3])