# Lesson 3 - Homework - Pandas and Numpy

### Hi again! :)

#### For today's homework, you will further explore the dataset recipe.csv. So start with importing the two key libraries: NumPy and pandas and loading the .csv file. Use the first column as index.

In [1]:
import numpy as np
import pandas as pd

In [9]:
df=pd.read_csv('data/Recipes.csv',index_col=0)
df[:3]

vegetarian  glutenFree  ...  CaffeineAmount  CaffeinepercentOfDailyNeed
0        True        True  ...             NaN                         NaN
1        True        True  ...             NaN                         NaN
2       False       False  ...            9.89                         3.3

[3 rows x 78 columns]

#### Drop all the columns that are of Boolean type. We won't need them.

#### Keep the new dataframe stored in the same variable as the first one.

In [11]:
df = df.select_dtypes(exclude=['bool'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 74 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   healthScore                         150 non-null    float64
 1   aggregateLikes                      150 non-null    int64  
 2   id                                  150 non-null    int64  
 3   title                               150 non-null    object 
 4   pricePerServing                     150 non-null    float64
 5   readyInMinutes                      150 non-null    int64  
 6   servings                            150 non-null    int64  
 7   sourceUrl                           150 non-null    object 
 8   CaloriesAmount                      150 non-null    float64
 9   CaloriespercentOfDailyNeed          150 non-null    float64
 10  FatAmount                           150 non-null    float64
 11  FatpercentOfDailyNeed               150 non-n

#### In some of the columns, there are less than 100 values available. Please drop them, too. We will learn how to deal with non-available values next time.

#### Keep the new dataframe stored in the same variable as the first one.

In [30]:
collist = [item for item in df.columns if df[item].value_counts().sum() < 100 ]
df.drop(columns = collist,inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 66 columns):
 #   Column                              Non-Null Count  Dtype  
---  ------                              --------------  -----  
 0   healthScore                         150 non-null    float64
 1   aggregateLikes                      150 non-null    int64  
 2   id                                  150 non-null    int64  
 3   title                               150 non-null    object 
 4   pricePerServing                     150 non-null    float64
 5   readyInMinutes                      150 non-null    int64  
 6   servings                            150 non-null    int64  
 7   sourceUrl                           150 non-null    object 
 8   CaloriesAmount                      150 non-null    float64
 9   CaloriespercentOfDailyNeed          150 non-null    float64
 10  FatAmount                           150 non-null    float64
 11  FatpercentOfDailyNeed               150 non-n

#### Enough dropping. How big is your DataFrame now?

In [31]:
df.shape

(150, 66)

#### Too big. The columns are fine, but we will restrict ourselves to 50 recipes. Please choose any 50 recipes (hint: maybe the first 50? :) ).

#### Keep the new dataframe stored in the same variable as the first one.

In [32]:
df=df[:50]
df.shape

(50, 66)

#### Display only the columns referring to Fiber.

In [37]:
df.loc[:, df.columns.str.startswith('Fiber')]

FiberAmount  FiberpercentOfDailyNeed
0          3.81                    15.22
1           NaN                      NaN
2          4.60                    18.40
3          3.45                    13.81
4          2.41                     9.64
5          2.95                    11.81
6          1.98                     7.94
7          1.56                     6.24
8          1.57                     6.27
9         27.10                   108.42
10        11.57                    46.28
11         1.54                     6.17
12         5.27                    21.07
13         2.57                    10.27
14         6.63                    26.53
15         4.52                    18.08
16          NaN                      NaN
17         3.19                    12.78
18         1.43                     5.71
19         1.78                     7.14
20         2.68                    10.71
21         1.09                     4.35
22         3.51                    14.03
23         0.68                     2.71
24         4.87                    19.49
25         1.72                     6.86
26         5.95                    23.82
27         6.96                    27.83
28         2.20                     8.79
29         3.12                    12.48
30        14.69                    58.75
31         4.34                    17.36
32         1.31                     5.23
33        11.79                    47.16
34         6.38                    25.51
35         1.14                     4.57
36         5.60                    22.39
37         5.79                    23.17
38         4.70                    18.81
39         1.71                     6.83
40         4.56                    18.23
41         0.81                     3.23
42         1.13                     4.50
43        12.40                    49.62
44         0.59                     2.36
45         0.91                     3.66
46         7.48                    29.91
47         1.37                     5.48
48         6.90                    27.59
49         1.92                     7.67

#### And now the columns referring to Fiber for recipes from rows numbered 10 to 30.

In [40]:
df.loc[10:30, df.columns.str.startswith('Fiber')]

FiberAmount  FiberpercentOfDailyNeed
10        11.57                    46.28
11         1.54                     6.17
12         5.27                    21.07
13         2.57                    10.27
14         6.63                    26.53
15         4.52                    18.08
16          NaN                      NaN
17         3.19                    12.78
18         1.43                     5.71
19         1.78                     7.14
20         2.68                    10.71
21         1.09                     4.35
22         3.51                    14.03
23         0.68                     2.71
24         4.87                    19.49
25         1.72                     6.86
26         5.95                    23.82
27         6.96                    27.83
28         2.20                     8.79
29         3.12                    12.48
30        14.69                    58.75

#### Cool. Now choose your favourite recipe and display only the respective row in the DataFrame.

In [58]:
df.iloc[39:40,:]

healthScore  aggregateLikes  ...  CalciumAmount CalciumpercentOfDailyNeed
39          7.0               6  ...          52.87                      5.29

[1 rows x 66 columns]

#### And now the columns referring to Fiber FOR your favourite recipe.

In [60]:
df.loc[39, df.columns.str.startswith('Fiber')]

FiberAmount                1.71
FiberpercentOfDailyNeed    6.83
Name: 39, dtype: object

#### One last thing. What is the difference between accessing the column "vegetarian" in those two ways:
- df["vegetarian"]
- df[["vegetarian"]]

#### (df is the name of your DataFrame).

Hint: what are the types of these two?

## Please remember that difference.

In [62]:
type(df['FiberAmount'])

pandas.core.series.Series

In [63]:
type(df[['FiberAmount']])

pandas.core.frame.DataFrame

# Exercises on Numpy

1. Write a NumPy program to create an array of the integers from 10 to 50

In [64]:
arrlist=[num for num in range(10,51)]
arr =np.array(arrlist)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

2. And print the Even and odd integers from the above array

In [66]:
for i in arr:
  if i % 2 == 0:
    print('Even: ',i)
  else:
    print('Odd: ', i)

Even:  10
Odd:  11
Even:  12
Odd:  13
Even:  14
Odd:  15
Even:  16
Odd:  17
Even:  18
Odd:  19
Even:  20
Odd:  21
Even:  22
Odd:  23
Even:  24
Odd:  25
Even:  26
Odd:  27
Even:  28
Odd:  29
Even:  30
Odd:  31
Even:  32
Odd:  33
Even:  34
Odd:  35
Even:  36
Odd:  37
Even:  38
Odd:  39
Even:  40
Odd:  41
Even:  42
Odd:  43
Even:  44
Odd:  45
Even:  46
Odd:  47
Even:  48
Odd:  49
Even:  50


3. Write a NumPy program to convert an array to a float type. 

__Expected output__:

Original array
[1, 2, 3, 4]

Array converted to a float type:
[ 1. 2. 3. 4.]

In [70]:
arr=arr.astype(float)
arr

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

4. Create a 2X2 integer array and print it's values and then print max along the axis 1 of that result.


array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49., 50.])

5. Create a 2-d array named ints and perform the following operations

- Print second row of ints

- Print all elements of ints that are greater than six

- Double every element of ints

- Replace the third column of ints

In [95]:
ints=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
ints

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [96]:
ints[1:2]

array([[ 6,  7,  8,  9, 10]])

In [97]:
ints[np.where(ints > 6)]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [98]:
ints=ints*2
ints

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [99]:
ints[2]=[3,4,5,6,7]
ints

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [ 3,  4,  5,  6,  7],
       [32, 34, 36, 38, 40]])

## #See you!!1